import Head from 'next/head'
import { useState } from 'react'
import Client from '../components/Client'
import { SocketProvider } from '../contexts/SocketProvider'
import config from '../lib/config'

export default function Home() {
    const [token, setToken] = useState('participant-token')

    const setTokenFromLogin = (newToken: string) => {
        setToken(newToken)
    }

    const endpoint = `https://${config.listenIp}:${config.listenPort}`

    return (
        <SocketProvider endpoint={endpoint} token={token}>
            <div className="flex flex-col items-center justify-center min-h-screen py-2">
                <Head>
                    <title>next + ts + twcss</title>
                    <meta
                        name="description"
                        content="Generated by create next app"
                    />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
                    <h1 className="text-6xl font-bold">
                        Mediasoup NextJs App
                        <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">
                            {' '}
                            😏
                        </a>
                    </h1>
                    <Client />
                </main>
            </div>
        </SocketProvider>
    )
}
